---
title: Lecture 4 -- Review questions
---

### 4.1 What is meant by the outflow limiting velocity of a nozzle?
### 4.2 What does the limiting velocity depend on?
### 4.3 What is the relationship between outflow velocity and limiting velocity?
### 4.4 Why are supersonic nozzles always considered in rocket engines?
### 4.5 What is the relationship between mass flow rate and pressure in the combustion chamber?
### 4.6 Write the expression for the mass flow rate in an ideal supersonic nozzle (i.e., isentropic and saturated) as a function of the characteristics of the propellant and the parameters in the combustion chamber.
### 4.7 What is the definition of thrust coefficient?
### 4.8 What is the definition of characteristic velocity?
### 4.9 Write the expression for specific impulse as a function of characteristic velocity and thrust coefficient.
### 4.10 On what factors does the thrust coefficient depend?
### 4.11 What is the effect of an increase in combustion chamber temperature on specific impulse? What is the effect of an increase in combustion chamber pressure? And what about an increase in the average molecular weight of the mixture?
### 4.12 What is the effect of an increase in combustion chamber temperature on thrust? What is the effect of an increase in combustion chamber pressure? And what about an increase in the average molecular weight of the mixture?
### 4.13 What is the limitation of conical nozzles? When can they prove to be advantageous?
### 4.14 What is the expansion ratio that maximizes the thrust coefficient of a rocket engine operating in the atmosphere?
### 4.15 On what basis is the expansion ratio of a rocket nozzle operating in a vacuum chosen?
### 4.16 Why was hydrogen considered as the propellant fluid for nuclear thermal rocket engines?
### 4.17 Which of the performance parameters ($F$, $I_{sp}$, $C_F$, $c^*$) depend on the pressure in the combustion chamber?
### 4.18 Which of the performance parameters ($F$, $I_{sp}$, $C_F$, $c^*$) depend on the ambient pressure?
### 4.19 Which of the performance parameters ($F$, $I_{sp}$, $C_F$, $c^*$) depend on the temperature in the combustion chamber?
### 4.20 Which of the performance parameters ($F$, $I_{sp}$, $C_F$, $c^*$) depend on the average molecular weight of the propellant fluid?
### 4.21 Which of the performance parameters ($F$, $I_{sp}$, $C_F$, $c^*$) depend on the ratio of specific heats $\gamma$?
### 4.22 Which of the performance parameters ($F$, $I_{sp}$, $C_F$, $c^*$) depend on the area ratio $\frac{A_2}{A_1}$?

